class Messages

  def instructions
   "    *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
    ------------------------ HOW TO PLAY MASTERMIND -------------------------
    Mastermind is a game where you must try to guess the secret combination.
    The combination will be randomly generated by the computer. Your goal
    will be to guess this secret combination in as few guesses as possible.
    "

  end

  def start_game_prompt
    "I have generated a beginner sequence with four elements made up of:\n
    (r)ed, (g)reen, (b)lue, and (y)ellow. Use (q)uit at any time to end the game.\n
    What's your guess?"
  end

  def main_menu
    "Welcome to MASTERMIND\n\nWould you like to (p)lay, read the (i)nstructions, or (q)uit?"
  end

  def goodbye
    "Goodbye"
  end
end
